force-app/main/default/objects/Poliza__c/Poliza__c.object-meta.xml
<CustomObject>
    <description>Objeto con datos de poliza de información asociada</description>
    <label>Poliza</label>
    <nameField>
        <label>Poliza Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polizas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Poliza__c/fields/Ano__c.field-meta.xml
<CustomField>
    <fullName>Ano__c</fullName>
    <label>Año</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Chasis__c.field-meta.xml
<CustomField>
    <fullName>Chasis__c</fullName>
    <label>Chasis</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Corredor__c.field-meta.xml
<CustomField>
    <fullName>Corredor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corredor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Polizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Direccion_Asegurado__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Asegurado__c</fullName>
    <label>Direccion Asegurado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Direccion_Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Beneficiario__c</fullName>
    <label>Direccion Beneficiario</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Nombre_Asegurado__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Asegurado__c</fullName>
    <label>Nombre Asegurado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Nombre_Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Beneficiario__c</fullName>
    <label>Nombre Beneficiario</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Numero_Motor__c.field-meta.xml
<CustomField>
    <fullName>Numero_Motor__c</fullName>
    <label>Numero Motor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Patente__c.field-meta.xml
<CustomField>
    <fullName>Patente__c</fullName>
    <label>Patente</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Rut_Asegurado__c.field-meta.xml
<CustomField>
    <fullName>Rut_Asegurado__c</fullName>
    <label>Rut Asegurado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Rut_Beneficiario__c.field-meta.xml
<CustomField>
    <fullName>Rut_Beneficiario__c</fullName>
    <label>Rut Beneficiario</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/uso__c.field-meta.xml
<CustomField>
    <fullName>uso__c</fullName>
    <label>uso</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Poliza__c/fields/Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Vigencia__c</fullName>
    <label>Vigencia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Siniestro__c/Siniestro__c.object-meta.xml
<CustomObject>
    <label>Siniestro</label>
    <nameField>
        <label>Sinisetro Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Siniestros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Siniestro__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Siniestros</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Siniestro__c/fields/Numero_Siniestro__c.field-meta.xml
<CustomField>
    <fullName>Numero_Siniestro__c</fullName>
    <label>Numero Siniestro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Siniestro__c/fields/Poliza__c.field-meta.xml
<CustomField>
    <fullName>Poliza__c</fullName>
    <label>Poliza</label>
    <referenceTo>Poliza__c</referenceTo>
    <relationshipName>Siniestros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateDocumentsWorkOrderController.cls
/**
 * @description       : 
 * @autor             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-27-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class CreateDocumentsWorkOrderController {
    @AuraEnabled(cacheable=true)
    public static List<Siniestro__c> getSiniestros(Id accountId) {
        return [

            SELECT Id, Numero_Siniestro__c
            FROM Siniestro__c
            WHERE Account__c = :accountId
        ];
    }

    @AuraEnabled
    public static Poliza__c getPolizaDetails(Id siniestroId) {
        Siniestro__c siniestro = [
            SELECT Poliza__c
            FROM Siniestro__c
            WHERE Id = :siniestroId
            LIMIT 1
        ];

        return [
            SELECT Id, Item__c, Vigencia__c, Corredor__c, Nombre_Asegurado__c, Rut_Asegurado__c, Direccion_Asegurado__c, 
                   Nombre_Beneficiario__c, Rut_Beneficiario__c, Direccion_Beneficiario__c, Tipo__c, Modelo__c, 
                   Patente__c, Chasis__c, Color__c, Marca__c, Ano__c, Numero_Motor__c, Uso__c
            FROM Poliza__c
            WHERE Id = :siniestro.Poliza__c
            LIMIT 1
        ];
    }
}